import { app } from 'electron';
import fs from 'fs-extra';
import path from 'path';

export interface AircraftRecord {
    registration: string;
    aircraftType: string;
    engine: string;
    category: string;
    year: string;
    livery: string;
}

const DEFAULT_DB: AircraftRecord[] = [
    { registration: 'G-DBCA', aircraftType: 'A319', engine: 'IAE', category: 'Mainline', year: '2003', livery: 'Chatham Dockyard' },
    { registration: 'G-DBCB', aircraftType: 'A319', engine: 'IAE', category: 'Mainline', year: '2004', livery: 'Chatham Dockyard' },
    { registration: 'G-DBCC', aircraftType: 'A319', engine: 'IAE', category: 'Mainline', year: '2004', livery: 'Chatham Dockyard' },
    { registration: 'G-DBCD', aircraftType: 'A319', engine: 'IAE', category: 'Mainline', year: '2005', livery: 'Chatham Dockyard' },
    { registration: 'G-DBCE', aircraftType: 'A319', engine: 'IAE', category: 'Mainline', year: '2005', livery: 'Chatham Dockyard' },
    { registration: 'G-DBCF', aircraftType: 'A319', engine: 'IAE', category: 'Mainline', year: '2005', livery: 'Chatham Dockyard' },
    { registration: 'G-DBCG', aircraftType: 'A319', engine: 'IAE', category: 'Mainline', year: '2006', livery: 'Chatham Dockyard' },
    { registration: 'G-DBCH', aircraftType: 'A319', engine: 'IAE', category: 'Mainline', year: '2006', livery: 'Chatham Dockyard' },
    { registration: 'G-DBCJ', aircraftType: 'A319', engine: 'IAE', category: 'Mainline', year: '2006', livery: 'Chatham Dockyard' },
    { registration: 'G-DBCK', aircraftType: 'A319', engine: 'IAE', category: 'Mainline', year: '2007', livery: 'Chatham Dockyard' },
    { registration: 'G-EUOG', aircraftType: 'A319', engine: 'IAE', category: 'Mainline', year: '2001', livery: 'Chatham Dockyard' },
    { registration: 'G-EUPD', aircraftType: 'A319', engine: 'IAE', category: 'Mainline', year: '1999', livery: 'Chatham Dockyard' },
    { registration: 'G-EUPG', aircraftType: 'A319', engine: 'IAE', category: 'Mainline', year: '2000', livery: 'Chatham Dockyard' },
    { registration: 'G-EUPJ', aircraftType: 'A319', engine: 'IAE', category: 'Mainline', year: '2000', livery: 'BEA Livery BA100' },
    { registration: 'G-EUPK', aircraftType: 'A319', engine: 'IAE', category: 'Mainline', year: '2000', livery: 'Chatham Dockyard' },
    { registration: 'G-EUPN', aircraftType: 'A319', engine: 'IAE', category: 'Mainline', year: '2000', livery: 'Chatham Dockyard' },
    { registration: 'G-EUPO', aircraftType: 'A319', engine: 'IAE', category: 'Mainline', year: '2000', livery: 'Chatham Dockyard' },
    { registration: 'G-EUPP', aircraftType: 'A319', engine: 'IAE', category: 'Mainline', year: '2000', livery: 'Chatham Dockyard' },
    { registration: 'G-EUPR', aircraftType: 'A319', engine: 'IAE', category: 'Mainline', year: '2000', livery: 'Chatham Dockyard' },
    { registration: 'G-EUPS', aircraftType: 'A319', engine: 'IAE', category: 'Mainline', year: '2000', livery: 'Chatham Dockyard' },
    { registration: 'G-EUPU', aircraftType: 'A319', engine: 'IAE', category: 'Mainline', year: '2000', livery: 'Chatham Dockyard' },
    { registration: 'G-EUPZ', aircraftType: 'A319', engine: 'IAE', category: 'Mainline', year: '2001', livery: 'Chatham Dockyard' },
    { registration: 'G-EUUA', aircraftType: 'A320', engine: 'IAE', category: 'Mainline', year: '2001', livery: 'Chatham Dockyard' },
    { registration: 'G-EUUB', aircraftType: 'A320', engine: 'IAE', category: 'Mainline', year: '2001', livery: 'Chatham Dockyard' },
    { registration: 'G-EUUC', aircraftType: 'A320', engine: 'IAE', category: 'Mainline', year: '2001', livery: 'Chatham Dockyard' },
    { registration: 'G-EUUD', aircraftType: 'A320', engine: 'IAE', category: 'Mainline', year: '2002', livery: 'Chatham Dockyard' },
    { registration: 'G-EUUE', aircraftType: 'A320', engine: 'IAE', category: 'Mainline', year: '2002', livery: 'Chatham Dockyard' },
    { registration: 'G-EUUF', aircraftType: 'A320', engine: 'IAE', category: 'Mainline', year: '2002', livery: 'Chatham Dockyard' },
    { registration: 'G-EUUG', aircraftType: 'A320', engine: 'IAE', category: 'Mainline', year: '2002', livery: 'Chatham Dockyard' },
    { registration: 'G-EUUH', aircraftType: 'A320', engine: 'IAE', category: 'Mainline', year: '2002', livery: 'Chatham Dockyard' },
    { registration: 'G-EUUI', aircraftType: 'A320', engine: 'IAE', category: 'Mainline', year: '2002', livery: 'Chatham Dockyard' },
    { registration: 'G-EUUJ', aircraftType: 'A320', engine: 'IAE', category: 'Mainline', year: '2002', livery: 'Chatham Dockyard' },
    { registration: 'G-EUUK', aircraftType: 'A320', engine: 'IAE', category: 'Mainline', year: '2002', livery: 'Chatham Dockyard' },
    { registration: 'G-EUUL', aircraftType: 'A320', engine: 'IAE', category: 'Mainline', year: '2002', livery: 'Chatham Dockyard' },
    { registration: 'G-EUUM', aircraftType: 'A320', engine: 'IAE', category: 'Mainline', year: '2002', livery: 'Chatham Dockyard' },
    { registration: 'G-EUUN', aircraftType: 'A320', engine: 'IAE', category: 'Mainline', year: '2002', livery: 'Chatham Dockyard' },
    { registration: 'G-EUUO', aircraftType: 'A320', engine: 'IAE', category: 'Mainline', year: '2003', livery: 'Chatham Dockyard' },
    { registration: 'G-EUUP', aircraftType: 'A320', engine: 'IAE', category: 'Mainline', year: '2003', livery: 'Chatham Dockyard' },
    { registration: 'G-EUUR', aircraftType: 'A320', engine: 'IAE', category: 'Mainline', year: '2003', livery: 'Chatham Dockyard' },
    { registration: 'G-EUUS', aircraftType: 'A320', engine: 'IAE', category: 'Mainline', year: '2007', livery: 'Chatham Dockyard' },
    { registration: 'G-EUUT', aircraftType: 'A320', engine: 'IAE', category: 'Mainline', year: '2007', livery: 'Chatham Dockyard' },
    { registration: 'G-EUUU', aircraftType: 'A320', engine: 'IAE', category: 'Mainline', year: '2008', livery: 'Chatham Dockyard' },
    { registration: 'G-EUUV', aircraftType: 'A320', engine: 'IAE', category: 'Euroflyer', year: '2008', livery: 'Chatham Dockyard' },
    { registration: 'G-EUUW', aircraftType: 'A320', engine: 'IAE', category: 'Euroflyer', year: '2008', livery: 'Chatham Dockyard' },
    { registration: 'G-EUUX', aircraftType: 'A320', engine: 'IAE', category: 'Euroflyer', year: '2008', livery: 'Chatham Dockyard' },
    { registration: 'G-EUUY', aircraftType: 'A320', engine: 'IAE', category: 'Euroflyer', year: '2008', livery: 'Chatham Dockyard' },
    { registration: 'G-EUUZ', aircraftType: 'A320', engine: 'IAE', category: 'Mainline', year: '2008', livery: 'Chatham Dockyard' },
    { registration: 'G-EUXC', aircraftType: 'A321', engine: 'IAE', category: 'Euroflyer', year: '2004', livery: 'Chatham Dockyard' },
    { registration: 'G-EUXD', aircraftType: 'A321', engine: 'IAE', category: 'Euroflyer', year: '2004', livery: 'Chatham Dockyard' },
    { registration: 'G-EUXE', aircraftType: 'A321', engine: 'IAE', category: 'Euroflyer', year: '2004', livery: 'Chatham Dockyard' },
    { registration: 'G-EUXF', aircraftType: 'A321', engine: 'IAE', category: 'Euroflyer', year: '2004', livery: 'Chatham Dockyard' },
    { registration: 'G-EUXG', aircraftType: 'A321', engine: 'IAE', category: 'Euroflyer', year: '2004', livery: 'Chatham Dockyard' },
    { registration: 'G-EUXH', aircraftType: 'A321', engine: 'IAE', category: 'Euroflyer', year: '2004', livery: 'Chatham Dockyard' },
    { registration: 'G-EUXI', aircraftType: 'A321', engine: 'IAE', category: 'Euroflyer', year: '2005', livery: 'Chatham Dockyard' },
    { registration: 'G-EUXJ', aircraftType: 'A321', engine: 'IAE', category: 'Euroflyer', year: '2007', livery: 'Chatham Dockyard' },
    { registration: 'G-EUXK', aircraftType: 'A321', engine: 'IAE', category: 'Euroflyer', year: '2007', livery: 'Chatham Dockyard' },
    { registration: 'G-EUXL', aircraftType: 'A321', engine: 'IAE', category: 'Euroflyer', year: '2007', livery: 'Chatham Dockyard' },
    { registration: 'G-EUXM', aircraftType: 'A321', engine: 'IAE', category: 'Euroflyer', year: '2007', livery: 'Chatham Dockyard' },
    { registration: 'G-EUYA', aircraftType: 'A320', engine: 'IAE', category: 'Mainline', year: '2008', livery: 'Chatham Dockyard' },
    { registration: 'G-EUYB', aircraftType: 'A320', engine: 'IAE', category: 'Mainline', year: '2008', livery: 'Chatham Dockyard' },
    { registration: 'G-EUYC', aircraftType: 'A320', engine: 'IAE', category: 'Mainline', year: '2008', livery: 'Chatham Dockyard' },
    { registration: 'G-EUYD', aircraftType: 'A320', engine: 'IAE', category: 'Mainline', year: '2008', livery: 'Chatham Dockyard' },
    { registration: 'G-EUYE', aircraftType: 'A320', engine: 'IAE', category: 'Mainline', year: '2009', livery: 'Chatham Dockyard' },
    { registration: 'G-EUYF', aircraftType: 'A320', engine: 'IAE', category: 'Mainline', year: '2010', livery: 'Chatham Dockyard' },
    { registration: 'G-EUYG', aircraftType: 'A320', engine: 'IAE', category: 'Mainline', year: '2010', livery: 'Chatham Dockyard' },
    { registration: 'G-EUYH', aircraftType: 'A320', engine: 'IAE', category: 'Mainline', year: '2010', livery: 'Chatham Dockyard' },
    { registration: 'G-EUYI', aircraftType: 'A320', engine: 'IAE', category: 'Mainline', year: '2010', livery: 'Chatham Dockyard' },
    { registration: 'G-EUYJ', aircraftType: 'A320', engine: 'IAE', category: 'Mainline', year: '2010', livery: 'Chatham Dockyard' },
    { registration: 'G-EUYK', aircraftType: 'A320', engine: 'IAE', category: 'Mainline', year: '2010', livery: 'Chatham Dockyard' },
    { registration: 'G-EUYL', aircraftType: 'A320', engine: 'IAE', category: 'Mainline', year: '2011', livery: 'Chatham Dockyard' },
    { registration: 'G-EUYM', aircraftType: 'A320', engine: 'IAE', category: 'Mainline', year: '2011', livery: 'Chatham Dockyard' },
    { registration: 'G-EUYN', aircraftType: 'A320', engine: 'IAE', category: 'Mainline', year: '2011', livery: 'Chatham Dockyard' },
    { registration: 'G-EUYO', aircraftType: 'A320', engine: 'IAE', category: 'Mainline', year: '2013', livery: 'Chatham Dockyard' },
    { registration: 'G-EUYP', aircraftType: 'A320', engine: 'IAE', category: 'Mainline', year: '2013', livery: 'One World Livery' },
    { registration: 'G-EUYR', aircraftType: 'A320', engine: 'IAE', category: 'Mainline', year: '2013', livery: 'One World Livery' },
    { registration: 'G-EUYS', aircraftType: 'A320', engine: 'IAE', category: 'Mainline', year: '2013', livery: 'One World Livery' },
    { registration: 'G-EUYT', aircraftType: 'A320', engine: 'IAE', category: 'Mainline', year: '2014', livery: 'Chatham Dockyard' },
    { registration: 'G-EUYU', aircraftType: 'A320', engine: 'IAE', category: 'Mainline', year: '2014', livery: 'Chatham Dockyard' },
    { registration: 'G-EUYV', aircraftType: 'A320', engine: 'IAE', category: 'Mainline', year: '2014', livery: 'Chatham Dockyard' },
    { registration: 'G-EUYW', aircraftType: 'A320', engine: 'IAE', category: 'Mainline', year: '2014', livery: 'Chatham Dockyard' },
    { registration: 'G-EUYX', aircraftType: 'A320', engine: 'IAE', category: 'Mainline', year: '2014', livery: 'Chatham Dockyard' },
    { registration: 'G-EUYY', aircraftType: 'A320', engine: 'IAE', category: 'Mainline', year: '2014', livery: 'Chatham Dockyard' },
    { registration: 'G-GATH', aircraftType: 'A320', engine: 'IAE', category: 'Euroflyer', year: '2001', livery: 'Chatham Dockyard' },
    { registration: 'G-GATJ', aircraftType: 'A320', engine: 'IAE', category: 'Euroflyer', year: '2001', livery: 'Chatham Dockyard' },
    { registration: 'G-GATK', aircraftType: 'A320', engine: 'IAE', category: 'Euroflyer', year: '2002', livery: 'Chatham Dockyard' },
    { registration: 'G-GATL', aircraftType: 'A320', engine: 'IAE', category: 'Euroflyer', year: '2002', livery: 'Chatham Dockyard' },
    { registration: 'G-GATM', aircraftType: 'A320', engine: 'IAE', category: 'Euroflyer', year: '2002', livery: 'Chatham Dockyard' },
    { registration: 'G-GATN', aircraftType: 'A320', engine: 'IAE', category: 'Euroflyer', year: '2001', livery: 'Chatham Dockyard' },
    { registration: 'G-GATP', aircraftType: 'A320', engine: 'IAE', category: 'Euroflyer', year: '2002', livery: 'Chatham Dockyard' },
    { registration: 'G-GATR', aircraftType: 'A320', engine: 'IAE', category: 'Euroflyer', year: '2002', livery: 'Chatham Dockyard' },
    { registration: 'G-GATS', aircraftType: 'A320', engine: 'IAE', category: 'Euroflyer', year: '2001', livery: 'Chatham Dockyard' },
    { registration: 'G-GATU', aircraftType: 'A320', engine: 'IAE', category: 'Euroflyer', year: '2007', livery: 'Chatham Dockyard' },
    { registration: 'G-LCAB', aircraftType: 'E190', engine: 'GE CF34', category: 'Cityflyer', year: '2011', livery: 'Operated By Cityflyer' },
    { registration: 'G-LCAC', aircraftType: 'E190', engine: 'GE CF34', category: 'Cityflyer', year: '2012', livery: 'Operated By Cityflyer' },
    { registration: 'G-LCAD', aircraftType: 'E190', engine: 'GE CF34', category: 'Cityflyer', year: '2012', livery: 'Operated By Cityflyer' },
    { registration: 'G-LCAE', aircraftType: 'E190', engine: 'GE CF34', category: 'Cityflyer', year: '2012', livery: 'Operated By Cityflyer' },
    { registration: 'G-LCAF', aircraftType: 'E190', engine: 'GE CF34', category: 'Cityflyer', year: '2012', livery: 'Operated By Cityflyer' },
    { registration: 'G-LCAG', aircraftType: 'E190', engine: 'GE CF34', category: 'Cityflyer', year: '2012', livery: 'Operated By Cityflyer' },
    { registration: 'G-LCAH', aircraftType: 'E190', engine: 'GE CF34', category: 'Cityflyer', year: '2012', livery: 'Operated By Cityflyer' },
    { registration: 'G-LCYJ', aircraftType: 'E190', engine: 'GE CF34', category: 'Cityflyer', year: '2010', livery: 'Operated By Cityflyer' },
    { registration: 'G-LCYK', aircraftType: 'E190', engine: 'GE CF34', category: 'Cityflyer', year: '2010', livery: 'Operated By Cityflyer' },
    { registration: 'G-LCYL', aircraftType: 'E190', engine: 'GE CF34', category: 'Cityflyer', year: '2010', livery: 'Operated By Cityflyer' },
    { registration: 'G-LCYM', aircraftType: 'E190', engine: 'GE CF34', category: 'Cityflyer', year: '2010', livery: 'Operated By Cityflyer' },
    { registration: 'G-LCYN', aircraftType: 'E190', engine: 'GE CF34', category: 'Cityflyer', year: '2010', livery: 'Operated By Cityflyer' },
    { registration: 'G-LCYO', aircraftType: 'E190', engine: 'GE CF34', category: 'Cityflyer', year: '2011', livery: 'Operated By Cityflyer' },
    { registration: 'G-LCYP', aircraftType: 'E190', engine: 'GE CF34', category: 'Cityflyer', year: '2011', livery: 'Operated By Cityflyer' },
    { registration: 'G-LCYR', aircraftType: 'E190', engine: 'GE CF34', category: 'Cityflyer', year: '2012', livery: 'Operated By Cityflyer' },
    { registration: 'G-LCYS', aircraftType: 'E190', engine: 'GE CF34', category: 'Cityflyer', year: '2014', livery: 'Operated By Cityflyer' },
    { registration: 'G-LCYT', aircraftType: 'E190', engine: 'GE CF34', category: 'Cityflyer', year: '2014', livery: 'Operated By Cityflyer' },
    { registration: 'G-LCYU', aircraftType: 'E190', engine: 'GE CF34', category: 'Cityflyer', year: '2014', livery: 'Operated By Cityflyer' },
    { registration: 'G-LCYV', aircraftType: 'E190', engine: 'GE CF34', category: 'Cityflyer', year: '2009', livery: 'Operated By Cityflyer' },
    { registration: 'G-LCYZ', aircraftType: 'E190', engine: 'GE CF34', category: 'Cityflyer', year: '2010', livery: 'Operated By Cityflyer' },
    { registration: 'G-MEDK', aircraftType: 'A320', engine: 'IAE', category: 'Euroflyer', year: '2005', livery: 'Chatham Dockyard' },
    { registration: 'G-NEOP', aircraftType: 'A21N', engine: 'CFM LEAP', category: 'Mainline', year: '2019', livery: 'Chatham Dockyard' },
    { registration: 'G-NEOR', aircraftType: 'A21N', engine: 'CFM LEAP', category: 'Mainline', year: '2018', livery: 'Chatham Dockyard' },
    { registration: 'G-NEOS', aircraftType: 'A21N', engine: 'CFM LEAP', category: 'Mainline', year: '2019', livery: 'Chatham Dockyard' },
    { registration: 'G-NEOT', aircraftType: 'A21N', engine: 'CFM LEAP', category: 'Mainline', year: '2019', livery: 'Chatham Dockyard' },
    { registration: 'G-NEOU', aircraftType: 'A21N', engine: 'CFM LEAP', category: 'Mainline', year: '2019', livery: 'Chatham Dockyard' },
    { registration: 'G-NEOV', aircraftType: 'A21N', engine: 'CFM LEAP', category: 'Mainline', year: '2019', livery: 'Chatham Dockyard' },
    { registration: 'G-NEOW', aircraftType: 'A21N', engine: 'CFM LEAP', category: 'Mainline', year: '2019', livery: 'Chatham Dockyard' },
    { registration: 'G-NEOX', aircraftType: 'A21N', engine: 'CFM LEAP', category: 'Mainline', year: '2019', livery: 'Chatham Dockyard' },
    { registration: 'G-NEOY', aircraftType: 'A21N', engine: 'CFM LEAP', category: 'Mainline', year: '2020', livery: 'Chatham Dockyard' },
    { registration: 'G-NEOZ', aircraftType: 'A21N', engine: 'CFM LEAP', category: 'Mainline', year: '2020', livery: 'Chatham Dockyard' },
    { registration: 'G-RAES', aircraftType: 'B772', engine: 'GE90', category: 'Mainline', year: '1997', livery: 'Chatham Dockyard' },
    { registration: 'G-STBA', aircraftType: 'B77W', engine: 'GE90', category: 'Mainline', year: '2010', livery: 'Chatham Dockyard' },
    { registration: 'G-STBB', aircraftType: 'B77W', engine: 'GE90', category: 'Mainline', year: '2010', livery: 'Chatham Dockyard' },
    { registration: 'G-STBC', aircraftType: 'B77W', engine: 'GE90', category: 'Mainline', year: '2010', livery: 'Chatham Dockyard' },
    { registration: 'G-STBD', aircraftType: 'B77W', engine: 'GE90', category: 'Mainline', year: '2011', livery: 'Chatham Dockyard' },
    { registration: 'G-STBE', aircraftType: 'B77W', engine: 'GE90', category: 'Mainline', year: '2011', livery: 'Chatham Dockyard' },
    { registration: 'G-STBF', aircraftType: 'B77W', engine: 'GE90', category: 'Mainline', year: '2012', livery: 'Chatham Dockyard' },
    { registration: 'G-STBG', aircraftType: 'B77W', engine: 'GE90', category: 'Mainline', year: '2013', livery: 'Chatham Dockyard' },
    { registration: 'G-STBH', aircraftType: 'B77W', engine: 'GE90', category: 'Mainline', year: '2013', livery: 'Chatham Dockyard' },
    { registration: 'G-STBI', aircraftType: 'B77W', engine: 'GE90', category: 'Mainline', year: '2014', livery: 'Chatham Dockyard' },
    { registration: 'G-STBJ', aircraftType: 'B77W', engine: 'GE90', category: 'Mainline', year: '2014', livery: 'Chatham Dockyard' },
    { registration: 'G-STBK', aircraftType: 'B77W', engine: 'GE90', category: 'Mainline', year: '2014', livery: 'Chatham Dockyard' },
    { registration: 'G-STBL', aircraftType: 'B77W', engine: 'GE90', category: 'Mainline', year: '2014', livery: 'Chatham Dockyard' },
    { registration: 'G-STBM', aircraftType: 'B77W', engine: 'GE90', category: 'Mainline', year: '2020', livery: 'Chatham Dockyard' },
    { registration: 'G-STBN', aircraftType: 'B77W', engine: 'GE90', category: 'Mainline', year: '2020', livery: 'Chatham Dockyard' },
    { registration: 'G-STBO', aircraftType: 'B77W', engine: 'GE90', category: 'Mainline', year: '2020', livery: 'Chatham Dockyard' },
    { registration: 'G-STBP', aircraftType: 'B77W', engine: 'GE90', category: 'Mainline', year: '2020', livery: 'Chatham Dockyard' },
    { registration: 'G-TNEA', aircraftType: 'A21N', engine: 'CFM LEAP', category: 'Mainline', year: '2023', livery: 'Chatham Dockyard' },
    { registration: 'G-TNEB', aircraftType: 'A21N', engine: 'CFM LEAP', category: 'Mainline', year: '2023', livery: 'Chatham Dockyard' },
    { registration: 'G-TNEC', aircraftType: 'A21N', engine: 'CFM LEAP', category: 'Mainline', year: '2023', livery: 'Chatham Dockyard' },
    { registration: 'G-TNED', aircraftType: 'A21N', engine: 'CFM LEAP', category: 'Mainline', year: '2024', livery: 'Chatham Dockyard' },
    { registration: 'G-TNEE', aircraftType: 'A21N', engine: 'CFM LEAP', category: 'Mainline', year: '2024', livery: 'Chatham Dockyard' },
    { registration: 'G-TNEF', aircraftType: 'A21N', engine: 'CFM LEAP', category: 'Mainline', year: '2025', livery: 'Chatham Dockyard' },
    { registration: 'G-TNEG', aircraftType: 'A21N', engine: 'CFM LEAP', category: 'Mainline', year: '2025', livery: 'Chatham Dockyard' },
    { registration: 'G-TNEH', aircraftType: 'A21N', engine: 'CFM LEAP', category: 'Mainline', year: '2025', livery: 'Chatham Dockyard' },
    { registration: 'G-TTNA', aircraftType: 'A20N', engine: 'CFM LEAP', category: 'Mainline', year: '2018', livery: 'BA Better World' },
    { registration: 'G-TTNB', aircraftType: 'A20N', engine: 'CFM LEAP', category: 'Mainline', year: '2018', livery: 'Chatham Dockyard' },
    { registration: 'G-TTNC', aircraftType: 'A20N', engine: 'CFM LEAP', category: 'Mainline', year: '2018', livery: 'Chatham Dockyard' },
    { registration: 'G-TTND', aircraftType: 'A20N', engine: 'CFM LEAP', category: 'Mainline', year: '2018', livery: 'Chatham Dockyard' },
    { registration: 'G-TTNE', aircraftType: 'A20N', engine: 'CFM LEAP', category: 'Mainline', year: '2018', livery: 'Chatham Dockyard' },
    { registration: 'G-TTNF', aircraftType: 'A20N', engine: 'CFM LEAP', category: 'Mainline', year: '2018', livery: 'Chatham Dockyard' },
    { registration: 'G-TTNG', aircraftType: 'A20N', engine: 'CFM LEAP', category: 'Mainline', year: '2018', livery: 'Chatham Dockyard' },
    { registration: 'G-TTNH', aircraftType: 'A20N', engine: 'CFM LEAP', category: 'Mainline', year: '2019', livery: 'Chatham Dockyard' },
    { registration: 'G-TTNI', aircraftType: 'A20N', engine: 'CFM LEAP', category: 'Mainline', year: '2019', livery: 'Chatham Dockyard' },
    { registration: 'G-TTNJ', aircraftType: 'A20N', engine: 'CFM LEAP', category: 'Mainline', year: '2019', livery: 'Chatham Dockyard' },
    { registration: 'G-TTNK', aircraftType: 'A20N', engine: 'CFM LEAP', category: 'Mainline', year: '2020', livery: 'Chatham Dockyard' },
    { registration: 'G-TTNL', aircraftType: 'A20N', engine: 'CFM LEAP', category: 'Mainline', year: '2020', livery: 'Chatham Dockyard' },
    { registration: 'G-TTNM', aircraftType: 'A20N', engine: 'CFM LEAP', category: 'Mainline', year: '2020', livery: 'Chatham Dockyard' },
    { registration: 'G-TTNN', aircraftType: 'A20N', engine: 'CFM LEAP', category: 'Mainline', year: '2021', livery: 'Chatham Dockyard' },
    { registration: 'G-TTNO', aircraftType: 'A20N', engine: 'CFM LEAP', category: 'Mainline', year: '2020', livery: 'Chatham Dockyard' },
    { registration: 'G-TTNP', aircraftType: 'A20N', engine: 'CFM LEAP', category: 'Mainline', year: '2021', livery: 'Chatham Dockyard' },
    { registration: 'G-TTNR', aircraftType: 'A20N', engine: 'CFM LEAP', category: 'Mainline', year: '2021', livery: 'Chatham Dockyard' },
    { registration: 'G-TTNS', aircraftType: 'A20N', engine: 'CFM LEAP', category: 'Mainline', year: '2022', livery: 'Chatham Dockyard' },
    { registration: 'G-TTNT', aircraftType: 'A20N', engine: 'CFM LEAP', category: 'Mainline', year: '2022', livery: 'Chatham Dockyard' },
    { registration: 'G-TTNU', aircraftType: 'A20N', engine: 'CFM LEAP', category: 'Mainline', year: '2023', livery: 'Chatham Dockyard' },
    { registration: 'G-TTNV', aircraftType: 'A20N', engine: 'CFM LEAP', category: 'Mainline', year: '2024', livery: 'Chatham Dockyard' },
    { registration: 'G-TTNW', aircraftType: 'A20N', engine: 'CFM LEAP', category: 'Mainline', year: '2024', livery: 'Chatham Dockyard' },
    { registration: 'G-TTNX', aircraftType: 'A20N', engine: 'CFM LEAP', category: 'Mainline', year: '2024', livery: 'Chatham Dockyard' },
    { registration: 'G-TTNY', aircraftType: 'A20N', engine: 'CFM LEAP', category: 'Mainline', year: '2024', livery: 'Chatham Dockyard' },
    { registration: 'G-TTNZ', aircraftType: 'A20N', engine: 'CFM LEAP', category: 'Mainline', year: '2024', livery: 'Chatham Dockyard' },
    { registration: 'G-TTOB', aircraftType: 'A320', engine: 'IAE', category: 'Mainline', year: '2001', livery: 'Chatham Dockyard' },
    { registration: 'G-TTOE', aircraftType: 'A320', engine: 'IAE', category: 'Mainline', year: '2002', livery: 'Chatham Dockyard' },
    { registration: 'G-TTSA', aircraftType: 'A20N', engine: 'CFM LEAP', category: 'Mainline', year: '2024', livery: 'Chatham Dockyard' },
    { registration: 'G-TTSC', aircraftType: 'A20N', engine: 'CFM LEAP', category: 'Mainline', year: '2025', livery: 'Chatham Dockyard' },
    { registration: 'G-TTSD', aircraftType: 'A20N', engine: 'CFM LEAP', category: 'Mainline', year: '2025', livery: 'Chatham Dockyard' },
    { registration: 'G-TTSE', aircraftType: 'A20N', engine: 'CFM LEAP', category: 'Mainline', year: '2025', livery: 'Chatham Dockyard' },
    { registration: 'G-TTSF', aircraftType: 'A20N', engine: 'CFM LEAP', category: 'Mainline', year: '2025', livery: 'Chatham Dockyard' },
    { registration: 'G-VIIA', aircraftType: 'B772', engine: 'GE90', category: 'Mainline', year: '1996', livery: 'Chatham Dockyard' },
    { registration: 'G-VIIB', aircraftType: 'B772', engine: 'GE90', category: 'Mainline', year: '1996', livery: 'Chatham Dockyard' },
    { registration: 'G-VIIC', aircraftType: 'B772', engine: 'GE90', category: 'Mainline', year: '1997', livery: 'Chatham Dockyard' },
    { registration: 'G-VIID', aircraftType: 'B772', engine: 'GE90', category: 'Mainline', year: '1997', livery: 'Chatham Dockyard' },
    { registration: 'G-VIIE', aircraftType: 'B772', engine: 'GE90', category: 'Mainline', year: '1997', livery: 'Chatham Dockyard' },
    { registration: 'G-VIIF', aircraftType: 'B772', engine: 'GE90', category: 'Mainline', year: '1997', livery: 'Chatham Dockyard' },
    { registration: 'G-VIIG', aircraftType: 'B772', engine: 'GE90', category: 'Mainline', year: '1997', livery: 'Chatham Dockyard' },
    { registration: 'G-VIIH', aircraftType: 'B772', engine: 'GE90', category: 'Mainline', year: '1997', livery: 'Chatham Dockyard' },
    { registration: 'G-VIIJ', aircraftType: 'B772', engine: 'GE90', category: 'Mainline', year: '1997', livery: 'Chatham Dockyard' },
    { registration: 'G-VIIK', aircraftType: 'B772', engine: 'GE90', category: 'Mainline', year: '1998', livery: 'Chatham Dockyard' },
    { registration: 'G-VIIL', aircraftType: 'B772', engine: 'GE90', category: 'Mainline', year: '1998', livery: 'Chatham Dockyard' },
    { registration: 'G-VIIM', aircraftType: 'B772', engine: 'GE90', category: 'Mainline', year: '1998', livery: 'Chatham Dockyard' },
    { registration: 'G-VIIN', aircraftType: 'B772', engine: 'GE90', category: 'Mainline', year: '1998', livery: 'Chatham Dockyard' },
    { registration: 'G-VIIO', aircraftType: 'B772', engine: 'GE90', category: 'Mainline', year: '1999', livery: 'Chatham Dockyard' },
    { registration: 'G-VIIP', aircraftType: 'B772', engine: 'GE90', category: 'Mainline', year: '1999', livery: 'Chatham Dockyard' },
    { registration: 'G-VIIR', aircraftType: 'B772', engine: 'GE90', category: 'Mainline', year: '1999', livery: 'Chatham Dockyard' },
    { registration: 'G-VIIS', aircraftType: 'B772', engine: 'GE90', category: 'Mainline', year: '1999', livery: 'Chatham Dockyard' },
    { registration: 'G-VIIT', aircraftType: 'B772', engine: 'GE90', category: 'Mainline', year: '1999', livery: 'Chatham Dockyard' },
    { registration: 'G-VIIU', aircraftType: 'B772', engine: 'GE90', category: 'Mainline', year: '1999', livery: 'Chatham Dockyard' },
    { registration: 'G-VIIV', aircraftType: 'B772', engine: 'GE90', category: 'Mainline', year: '1999', livery: 'Chatham Dockyard' },
    { registration: 'G-VIIW', aircraftType: 'B772', engine: 'GE90', category: 'Mainline', year: '1999', livery: 'Chatham Dockyard' },
    { registration: 'G-VIIX', aircraftType: 'B772', engine: 'GE90', category: 'Mainline', year: '1999', livery: 'Chatham Dockyard' },
    { registration: 'G-VIIY', aircraftType: 'B772', engine: 'GE90', category: 'Mainline', year: '1999', livery: 'Chatham Dockyard' },
    { registration: 'G-XLEA', aircraftType: 'A388', engine: 'RR Trent 900', category: 'Mainline', year: '2012', livery: 'Chatham Dockyard' },
    { registration: 'G-XLEB', aircraftType: 'A388', engine: 'RR Trent 900', category: 'Mainline', year: '2013', livery: 'Chatham Dockyard' },
    { registration: 'G-XLEC', aircraftType: 'A388', engine: 'RR Trent 900', category: 'Mainline', year: '2013', livery: 'Chatham Dockyard' },
    { registration: 'G-XLED', aircraftType: 'A388', engine: 'RR Trent 900', category: 'Mainline', year: '2013', livery: 'Chatham Dockyard' },
    { registration: 'G-XLEE', aircraftType: 'A388', engine: 'RR Trent 900', category: 'Mainline', year: '2013', livery: 'Chatham Dockyard' },
    { registration: 'G-XLEF', aircraftType: 'A388', engine: 'RR Trent 900', category: 'Mainline', year: '2014', livery: 'Chatham Dockyard' },
    { registration: 'G-XLEG', aircraftType: 'A388', engine: 'RR Trent 900', category: 'Mainline', year: '2014', livery: 'Chatham Dockyard' },
    { registration: 'G-XLEH', aircraftType: 'A388', engine: 'RR Trent 900', category: 'Mainline', year: '2014', livery: 'Chatham Dockyard' },
    { registration: 'G-XLEI', aircraftType: 'A388', engine: 'RR Trent 900', category: 'Mainline', year: '2014', livery: 'Chatham Dockyard' },
    { registration: 'G-XLEJ', aircraftType: 'A388', engine: 'RR Trent 900', category: 'Mainline', year: '2015', livery: 'Chatham Dockyard' },
    { registration: 'G-XLEK', aircraftType: 'A388', engine: 'RR Trent 900', category: 'Mainline', year: '2015', livery: 'Chatham Dockyard' },
    { registration: 'G-XLEL', aircraftType: 'A388', engine: 'RR Trent 900', category: 'Mainline', year: '2016', livery: 'Chatham Dockyard' },
    { registration: 'G-XWBA', aircraftType: 'A35K', engine: 'RR Trent XWB-97', category: 'Mainline', year: '2019', livery: 'Chatham Dockyard' },
    { registration: 'G-XWBB', aircraftType: 'A35K', engine: 'RR Trent XWB-97', category: 'Mainline', year: '2019', livery: 'Chatham Dockyard' },
    { registration: 'G-XWBC', aircraftType: 'A35K', engine: 'RR Trent XWB-97', category: 'Mainline', year: '2019', livery: 'Chatham Dockyard' },
    { registration: 'G-XWBD', aircraftType: 'A35K', engine: 'RR Trent XWB-97', category: 'Mainline', year: '2019', livery: 'Chatham Dockyard' },
    { registration: 'G-XWBE', aircraftType: 'A35K', engine: 'RR Trent XWB-97', category: 'Mainline', year: '2020', livery: 'Chatham Dockyard' },
    { registration: 'G-XWBF', aircraftType: 'A35K', engine: 'RR Trent XWB-97', category: 'Mainline', year: '2020', livery: 'Chatham Dockyard' },
    { registration: 'G-XWBG', aircraftType: 'A35K', engine: 'RR Trent XWB-97', category: 'Mainline', year: '2020', livery: 'Chatham Dockyard' },
    { registration: 'G-XWBH', aircraftType: 'A35K', engine: 'RR Trent XWB-97', category: 'Mainline', year: '2020', livery: 'Chatham Dockyard' },
    { registration: 'G-XWBI', aircraftType: 'A35K', engine: 'RR Trent XWB-97', category: 'Mainline', year: '2021', livery: 'Chatham Dockyard' },
    { registration: 'G-XWBJ', aircraftType: 'A35K', engine: 'RR Trent XWB-97', category: 'Mainline', year: '2022', livery: 'Chatham Dockyard' },
    { registration: 'G-XWBK', aircraftType: 'A35K', engine: 'RR Trent XWB-97', category: 'Mainline', year: '2022', livery: 'Chatham Dockyard' },
    { registration: 'G-XWBL', aircraftType: 'A35K', engine: 'RR Trent XWB-97', category: 'Mainline', year: '2022', livery: 'Chatham Dockyard' },
    { registration: 'G-XWBM', aircraftType: 'A35K', engine: 'RR Trent XWB-97', category: 'Mainline', year: '2022', livery: 'Chatham Dockyard' },
    { registration: 'G-XWBN', aircraftType: 'A35K', engine: 'RR Trent XWB-97', category: 'Mainline', year: '2023', livery: 'Chatham Dockyard' },
    { registration: 'G-XWBO', aircraftType: 'A35K', engine: 'RR Trent XWB-97', category: 'Mainline', year: '2023', livery: 'Chatham Dockyard' },
    { registration: 'G-XWBP', aircraftType: 'A35K', engine: 'RR Trent XWB-97', category: 'Mainline', year: '2023', livery: 'Chatham Dockyard' },
    { registration: 'G-XWBR', aircraftType: 'A35K', engine: 'RR Trent XWB-97', category: 'Mainline', year: '2023', livery: 'Chatham Dockyard' },
    { registration: 'G-XWBS', aircraftType: 'A35K', engine: 'RR Trent XWB-97', category: 'Mainline', year: '2024', livery: 'Chatham Dockyard' },
    { registration: 'G-YMMA', aircraftType: 'B772', engine: 'RR Trent 800', category: 'Mainline', year: '1999', livery: 'Chatham Dockyard' },
    { registration: 'G-YMMB', aircraftType: 'B772', engine: 'RR Trent 800', category: 'Mainline', year: '2000', livery: 'Chatham Dockyard' },
    { registration: 'G-YMMC', aircraftType: 'B772', engine: 'RR Trent 800', category: 'Mainline', year: '2000', livery: 'Chatham Dockyard' },
    { registration: 'G-YMMD', aircraftType: 'B772', engine: 'RR Trent 800', category: 'Mainline', year: '2000', livery: 'Chatham Dockyard' },
    { registration: 'G-YMME', aircraftType: 'B772', engine: 'RR Trent 800', category: 'Mainline', year: '2000', livery: 'Chatham Dockyard' },
    { registration: 'G-YMMF', aircraftType: 'B772', engine: 'RR Trent 800', category: 'Mainline', year: '2000', livery: 'Oneworld Alliance Livery' },
    { registration: 'G-YMMG', aircraftType: 'B772', engine: 'RR Trent 800', category: 'Mainline', year: '2000', livery: 'Chatham Dockyard' },
    { registration: 'G-YMMH', aircraftType: 'B772', engine: 'RR Trent 800', category: 'Mainline', year: '2000', livery: 'Chatham Dockyard' },
    { registration: 'G-YMMI', aircraftType: 'B772', engine: 'RR Trent 800', category: 'Mainline', year: '2000', livery: 'Chatham Dockyard' },
    { registration: 'G-YMMJ', aircraftType: 'B772', engine: 'RR Trent 800', category: 'Mainline', year: '2000', livery: 'Chatham Dockyard' },
    { registration: 'G-YMMK', aircraftType: 'B772', engine: 'RR Trent 800', category: 'Mainline', year: '2000', livery: 'Chatham Dockyard' },
    { registration: 'G-YMML', aircraftType: 'B772', engine: 'RR Trent 800', category: 'Mainline', year: '2001', livery: 'Great Festival of Creativity in Shanghai' },
    { registration: 'G-YMMN', aircraftType: 'B772', engine: 'RR Trent 800', category: 'Mainline', year: '2001', livery: 'Chatham Dockyard' },
    { registration: 'G-YMMO', aircraftType: 'B772', engine: 'RR Trent 800', category: 'Mainline', year: '2001', livery: 'Chatham Dockyard' },
    { registration: 'G-YMMP', aircraftType: 'B772', engine: 'RR Trent 800', category: 'Mainline', year: '2001', livery: 'Chatham Dockyard' },
    { registration: 'G-YMMR', aircraftType: 'B772', engine: 'RR Trent 800', category: 'Mainline', year: '2009', livery: 'Oneworld Alliance Livery' },
    { registration: 'G-YMMS', aircraftType: 'B772', engine: 'RR Trent 800', category: 'Mainline', year: '2009', livery: 'Chatham Dockyard' },
    { registration: 'G-YMMT', aircraftType: 'B772', engine: 'RR Trent 800', category: 'Mainline', year: '2009', livery: 'Oneworld Alliance Livery' },
    { registration: 'G-YMMU', aircraftType: 'B772', engine: 'RR Trent 800', category: 'Mainline', year: '2009', livery: 'Oneworld Alliance Livery' },
    { registration: 'G-ZBJA', aircraftType: 'B788', engine: 'RR Trent 1000-R', category: 'Mainline', year: '2013', livery: 'Chatham Dockyard' },
    { registration: 'G-ZBJB', aircraftType: 'B788', engine: 'RR Trent 1000-R', category: 'Mainline', year: '2013', livery: 'Chatham Dockyard' },
    { registration: 'G-ZBJC', aircraftType: 'B788', engine: 'RR Trent 1000-R', category: 'Mainline', year: '2013', livery: 'Chatham Dockyard' },
    { registration: 'G-ZBJD', aircraftType: 'B788', engine: 'RR Trent 1000-R', category: 'Mainline', year: '2013', livery: 'Chatham Dockyard' },
    { registration: 'G-ZBJE', aircraftType: 'B788', engine: 'RR Trent 1000-R', category: 'Mainline', year: '2014', livery: 'Chatham Dockyard' },
    { registration: 'G-ZBJF', aircraftType: 'B788', engine: 'RR Trent 1000-R', category: 'Mainline', year: '2014', livery: 'Chatham Dockyard' },
    { registration: 'G-ZBJG', aircraftType: 'B788', engine: 'RR Trent 1000-R', category: 'Mainline', year: '2014', livery: 'Chatham Dockyard' },
    { registration: 'G-ZBJH', aircraftType: 'B788', engine: 'RR Trent 1000-R', category: 'Mainline', year: '2014', livery: 'Chatham Dockyard' },
    { registration: 'G-ZBJI', aircraftType: 'B788', engine: 'RR Trent 1000-R', category: 'Mainline', year: '2017', livery: 'Chatham Dockyard' },
    { registration: 'G-ZBJJ', aircraftType: 'B788', engine: 'RR Trent 1000-R', category: 'Mainline', year: '2018', livery: 'Chatham Dockyard' },
    { registration: 'G-ZBJK', aircraftType: 'B788', engine: 'RR Trent 1000-R', category: 'Mainline', year: '2018', livery: 'Chatham Dockyard' },
    { registration: 'G-ZBJM', aircraftType: 'B788', engine: 'RR Trent 1000-R', category: 'Mainline', year: '2018', livery: 'Chatham Dockyard' },
    { registration: 'G-ZBKA', aircraftType: 'B789', engine: 'RR Trent 1000-D3', category: 'Mainline', year: '2015', livery: 'Chatham Dockyard' },
    { registration: 'G-ZBKB', aircraftType: 'B789', engine: 'RR Trent 1000-D3', category: 'Mainline', year: '2015', livery: 'Chatham Dockyard' },
    { registration: 'G-ZBKC', aircraftType: 'B789', engine: 'RR Trent 1000-D3', category: 'Mainline', year: '2015', livery: 'Chatham Dockyard' },
    { registration: 'G-ZBKD', aircraftType: 'B789', engine: 'RR Trent 1000-D3', category: 'Mainline', year: '2015', livery: 'Chatham Dockyard' },
    { registration: 'G-ZBKE', aircraftType: 'B789', engine: 'RR Trent 1000-D3', category: 'Mainline', year: '2015', livery: 'Chatham Dockyard' },
    { registration: 'G-ZBKF', aircraftType: 'B789', engine: 'RR Trent 1000-D3', category: 'Mainline', year: '2016', livery: 'Chatham Dockyard' },
    { registration: 'G-ZBKG', aircraftType: 'B789', engine: 'RR Trent 1000-D3', category: 'Mainline', year: '2016', livery: 'Chatham Dockyard' },
    { registration: 'G-ZBKH', aircraftType: 'B789', engine: 'RR Trent 1000-D3', category: 'Mainline', year: '2016', livery: 'Chatham Dockyard' },
    { registration: 'G-ZBKI', aircraftType: 'B789', engine: 'RR Trent 1000-D3', category: 'Mainline', year: '2016', livery: 'Chatham Dockyard' },
    { registration: 'G-ZBKJ', aircraftType: 'B789', engine: 'RR Trent 1000-D3', category: 'Mainline', year: '2016', livery: 'Chatham Dockyard' },
    { registration: 'G-ZBKK', aircraftType: 'B789', engine: 'RR Trent 1000-D3', category: 'Mainline', year: '2016', livery: 'Chatham Dockyard' },
    { registration: 'G-ZBKL', aircraftType: 'B789', engine: 'RR Trent 1000-D3', category: 'Mainline', year: '2016', livery: 'Chatham Dockyard' },
    { registration: 'G-ZBKM', aircraftType: 'B789', engine: 'RR Trent 1000-D3', category: 'Mainline', year: '2016', livery: 'Chatham Dockyard' },
    { registration: 'G-ZBKN', aircraftType: 'B789', engine: 'RR Trent 1000-D3', category: 'Mainline', year: '2016', livery: 'Chatham Dockyard' },
    { registration: 'G-ZBKO', aircraftType: 'B789', engine: 'RR Trent 1000-D3', category: 'Mainline', year: '2016', livery: 'Chatham Dockyard' },
    { registration: 'G-ZBKP', aircraftType: 'B789', engine: 'RR Trent 1000-D3', category: 'Mainline', year: '2016', livery: 'Chatham Dockyard' },
    { registration: 'G-ZBKR', aircraftType: 'B789', engine: 'RR Trent 1000-D3', category: 'Mainline', year: '2018', livery: 'Chatham Dockyard' },
    { registration: 'G-ZBKS', aircraftType: 'B789', engine: 'RR Trent 1000-D3', category: 'Mainline', year: '2018', livery: 'Chatham Dockyard' },
    { registration: 'G-ZBLA', aircraftType: 'B78X', engine: 'RR Trent 1000-R', category: 'Mainline', year: '2020', livery: 'Chatham Dockyard' },
    { registration: 'G-ZBLB', aircraftType: 'B78X', engine: 'RR Trent 1000-R', category: 'Mainline', year: '2020', livery: 'Chatham Dockyard' },
    { registration: 'G-ZBLC', aircraftType: 'B78X', engine: 'RR Trent 1000-R', category: 'Mainline', year: '2020', livery: 'Chatham Dockyard' },
    { registration: 'G-ZBLD', aircraftType: 'B78X', engine: 'RR Trent 1000-R', category: 'Mainline', year: '2020', livery: 'Chatham Dockyard' },
    { registration: 'G-ZBLE', aircraftType: 'B78X', engine: 'RR Trent 1000-R', category: 'Mainline', year: '2021', livery: 'Chatham Dockyard' },
    { registration: 'G-ZBLF', aircraftType: 'B78X', engine: 'RR Trent 1000-R', category: 'Mainline', year: '2021', livery: 'Chatham Dockyard' },
    { registration: 'G-ZBLG', aircraftType: 'B78X', engine: 'RR Trent 1000-R', category: 'Mainline', year: '2021', livery: 'Chatham Dockyard' },
];

const DB_PATH = () => path.join(app.getPath('userData'), 'meta-aircraft-db.json');

export async function loadMetaDb(): Promise<AircraftRecord[]> {
    try {
        if (await fs.pathExists(DB_PATH())) {
            return await fs.readJson(DB_PATH()) as AircraftRecord[];
        }
    } catch { /* fall through to default */ }
    return [...DEFAULT_DB];
}

export async function saveMetaDb(records: AircraftRecord[]): Promise<void> {
    await fs.writeJson(DB_PATH(), records, { spaces: 2 });
}
